gamepad_driver = all
global_prep_cmd = [{"do":"powershell.exe -executionpolicy bypass -file \"F:\\Sunshine\\ResolutionAutomation\\StreamMonitor.ps1\" -n ResolutionMatcher","elevated":false,"undo":"powershell.exe -executionpolicy bypass -file \"F:\\Sunshine\\ResolutionAutomation\\Helpers.ps1\" -n ResolutionMatcher -t 1"}]
